TEMPLATE = app
CONFIG += console
CONFIG -= app_bundle
CONFIG -= qt

LIBS += -L$$PWD/lib/ -lmingw32 -lSDL2main -lSDL2

SOURCES += \
        demos/lvgl_app/lvgl_app.c/menu_app.c \
        demos/lvgl_app/lvgl_app.c/oscilloscope_app.c \
        demos/lvgl_app/lvgl_app.c/power_app.c \
        demos/lvgl_app/lvgl_app.c/screen.c \
        demos/lvgl_app/lvgl_app.c/signal_app.c \
        demos/lvgl_app/lvgl_app_else/menu.c \
        demos/lvgl_app/lvgl_app_else/menu1.c \
        demos/lvgl_app/lvgl_app_else/myFont.c \
        demos/lvgl_app/lvgl_app_else/oscilloscope.c \
        demos/lvgl_app/lvgl_app_else/oscilloscope1.c \
        demos/lvgl_app/lvgl_app_else/oscilloscope_set.c \
        demos/lvgl_app/lvgl_app_else/power.c \
        demos/lvgl_app/lvgl_app_else/power1.c \
        demos/lvgl_app/lvgl_app_else/power_host.c \
        demos/lvgl_app/lvgl_app_else/signal1.c \
        demos/lvgl_app/lvgl_app_else/signal_ch.c \
        demos/lvgl_app/lvgl_app_else/signal_ch1.c \
        demos/lvgl_app/lvgl_app_else/signal_ch2.c \
        demos/lvgl_app/lvgl_app_else/signal_set.c \
        demos/lvgl_app/lvgl_app_else/signal_tt.c \
        demos/lvgl_app/lvgl_app_else/signal_wave1.c \
        demos/lvgl_app/lvgl_app_else/signal_wave2.c \
        demos/lvgl_app/lvgl_app_else/title_menu.c \
        demos/lvgl_app/lvgl_app_else/title_oscilloscope.c \
        demos/lvgl_app/lvgl_app_else/title_power.c \
        demos/lvgl_app/lvgl_app_else/title_signa.c \
        lv_drivers/display/GC9A01.c \
        lv_drivers/display/ILI9341.c \
        lv_drivers/display/R61581.c \
        lv_drivers/display/SHARP_MIP.c \
        lv_drivers/display/SSD1963.c \
        lv_drivers/display/ST7565.c \
        lv_drivers/display/UC1610.c \
        lv_drivers/display/drm.c \
        lv_drivers/display/fbdev.c \
        lv_drivers/gtkdrv/gtkdrv.c \
        lv_drivers/indev/AD_touch.c \
        lv_drivers/indev/FT5406EE8.c \
        lv_drivers/indev/XPT2046.c \
        lv_drivers/indev/evdev.c \
        lv_drivers/indev/libinput.c \
        lv_drivers/indev/xkb.c \
        lv_drivers/sdl/sdl.c \
        lv_drivers/sdl/sdl_gpu.c \
        lv_drivers/wayland/wayland.c \
        lv_drivers/win32drv/win32drv.c \
        lv_drivers/win_drv.c \
        main.c \
        mouse_cursor_icon.c \
        src/core/lv_disp.c \
        src/core/lv_event.c \
        src/core/lv_group.c \
        src/core/lv_indev.c \
        src/core/lv_indev_scroll.c \
        src/core/lv_obj.c \
        src/core/lv_obj_class.c \
        src/core/lv_obj_draw.c \
        src/core/lv_obj_pos.c \
        src/core/lv_obj_scroll.c \
        src/core/lv_obj_style.c \
        src/core/lv_obj_style_gen.c \
        src/core/lv_obj_tree.c \
        src/core/lv_refr.c \
        src/core/lv_theme.c \
        src/draw/lv_draw.c \
        src/draw/lv_draw_arc.c \
        src/draw/lv_draw_img.c \
        src/draw/lv_draw_label.c \
        src/draw/lv_draw_line.c \
        src/draw/lv_draw_mask.c \
        src/draw/lv_draw_rect.c \
        src/draw/lv_draw_triangle.c \
        src/draw/lv_img_buf.c \
        src/draw/lv_img_cache.c \
        src/draw/lv_img_decoder.c \
        src/draw/nxp_pxp/lv_gpu_nxp_pxp.c \
        src/draw/nxp_pxp/lv_gpu_nxp_pxp_osa.c \
        src/draw/nxp_vglite/lv_gpu_nxp_vglite.c \
        src/draw/sdl/lv_draw_sdl.c \
        src/draw/sdl/lv_draw_sdl_arc.c \
        src/draw/sdl/lv_draw_sdl_bg.c \
        src/draw/sdl/lv_draw_sdl_composite.c \
        src/draw/sdl/lv_draw_sdl_img.c \
        src/draw/sdl/lv_draw_sdl_label.c \
        src/draw/sdl/lv_draw_sdl_line.c \
        src/draw/sdl/lv_draw_sdl_mask.c \
        src/draw/sdl/lv_draw_sdl_polygon.c \
        src/draw/sdl/lv_draw_sdl_rect.c \
        src/draw/sdl/lv_draw_sdl_stack_blur.c \
        src/draw/sdl/lv_draw_sdl_texture_cache.c \
        src/draw/sdl/lv_draw_sdl_utils.c \
        src/draw/stm32_dma2d/lv_gpu_stm32_dma2d.c \
        src/draw/sw/lv_draw_sw.c \
        src/draw/sw/lv_draw_sw_arc.c \
        src/draw/sw/lv_draw_sw_blend.c \
        src/draw/sw/lv_draw_sw_dither.c \
        src/draw/sw/lv_draw_sw_gradient.c \
        src/draw/sw/lv_draw_sw_img.c \
        src/draw/sw/lv_draw_sw_letter.c \
        src/draw/sw/lv_draw_sw_line.c \
        src/draw/sw/lv_draw_sw_polygon.c \
        src/draw/sw/lv_draw_sw_rect.c \
        src/extra/layouts/flex/lv_flex.c \
        src/extra/layouts/grid/lv_grid.c \
        src/extra/libs/bmp/lv_bmp.c \
        src/extra/libs/ffmpeg/lv_ffmpeg.c \
        src/extra/libs/freetype/lv_freetype.c \
        src/extra/libs/fsdrv/lv_fs_fatfs.c \
        src/extra/libs/fsdrv/lv_fs_posix.c \
        src/extra/libs/fsdrv/lv_fs_stdio.c \
        src/extra/libs/fsdrv/lv_fs_win32.c \
        src/extra/libs/gif/gifdec.c \
        src/extra/libs/gif/lv_gif.c \
        src/extra/libs/png/lodepng.c \
        src/extra/libs/png/lv_png.c \
        src/extra/libs/qrcode/lv_qrcode.c \
        src/extra/libs/qrcode/qrcodegen.c \
        src/extra/libs/rlottie/lv_rlottie.c \
        src/extra/libs/sjpg/lv_sjpg.c \
        src/extra/libs/sjpg/tjpgd.c \
        src/extra/lv_extra.c \
        src/extra/others/gridnav/lv_gridnav.c \
        src/extra/others/monkey/lv_monkey.c \
        src/extra/others/snapshot/lv_snapshot.c \
        src/extra/themes/basic/lv_theme_basic.c \
        src/extra/themes/default/lv_theme_default.c \
        src/extra/themes/mono/lv_theme_mono.c \
        src/extra/widgets/animimg/lv_animimg.c \
        src/extra/widgets/calendar/lv_calendar.c \
        src/extra/widgets/calendar/lv_calendar_header_arrow.c \
        src/extra/widgets/calendar/lv_calendar_header_dropdown.c \
        src/extra/widgets/chart/lv_chart.c \
        src/extra/widgets/colorwheel/lv_colorwheel.c \
        src/extra/widgets/imgbtn/lv_imgbtn.c \
        src/extra/widgets/keyboard/lv_keyboard.c \
        src/extra/widgets/led/lv_led.c \
        src/extra/widgets/list/lv_list.c \
        src/extra/widgets/menu/lv_menu.c \
        src/extra/widgets/meter/lv_meter.c \
        src/extra/widgets/msgbox/lv_msgbox.c \
        src/extra/widgets/span/lv_span.c \
        src/extra/widgets/spinbox/lv_spinbox.c \
        src/extra/widgets/spinner/lv_spinner.c \
        src/extra/widgets/tabview/lv_tabview.c \
        src/extra/widgets/tileview/lv_tileview.c \
        src/extra/widgets/win/lv_win.c \
        src/font/lv_font.c \
        src/font/lv_font_dejavu_16_persian_hebrew.c \
        src/font/lv_font_fmt_txt.c \
        src/font/lv_font_loader.c \
        src/font/lv_font_montserrat_10.c \
        src/font/lv_font_montserrat_12.c \
        src/font/lv_font_montserrat_12_subpx.c \
        src/font/lv_font_montserrat_14.c \
        src/font/lv_font_montserrat_16.c \
        src/font/lv_font_montserrat_18.c \
        src/font/lv_font_montserrat_20.c \
        src/font/lv_font_montserrat_22.c \
        src/font/lv_font_montserrat_24.c \
        src/font/lv_font_montserrat_26.c \
        src/font/lv_font_montserrat_28.c \
        src/font/lv_font_montserrat_28_compressed.c \
        src/font/lv_font_montserrat_30.c \
        src/font/lv_font_montserrat_32.c \
        src/font/lv_font_montserrat_34.c \
        src/font/lv_font_montserrat_36.c \
        src/font/lv_font_montserrat_38.c \
        src/font/lv_font_montserrat_40.c \
        src/font/lv_font_montserrat_42.c \
        src/font/lv_font_montserrat_44.c \
        src/font/lv_font_montserrat_46.c \
        src/font/lv_font_montserrat_48.c \
        src/font/lv_font_montserrat_8.c \
        src/font/lv_font_simsun_16_cjk.c \
        src/font/lv_font_unscii_16.c \
        src/font/lv_font_unscii_8.c \
        src/hal/lv_hal_disp.c \
        src/hal/lv_hal_indev.c \
        src/hal/lv_hal_tick.c \
        src/misc/lv_anim.c \
        src/misc/lv_anim_timeline.c \
        src/misc/lv_area.c \
        src/misc/lv_async.c \
        src/misc/lv_bidi.c \
        src/misc/lv_color.c \
        src/misc/lv_fs.c \
        src/misc/lv_gc.c \
        src/misc/lv_ll.c \
        src/misc/lv_log.c \
        src/misc/lv_lru.c \
        src/misc/lv_math.c \
        src/misc/lv_mem.c \
        src/misc/lv_printf.c \
        src/misc/lv_style.c \
        src/misc/lv_style_gen.c \
        src/misc/lv_templ.c \
        src/misc/lv_timer.c \
        src/misc/lv_tlsf.c \
        src/misc/lv_txt.c \
        src/misc/lv_txt_ap.c \
        src/misc/lv_utils.c \
        src/widgets/lv_arc.c \
        src/widgets/lv_bar.c \
        src/widgets/lv_btn.c \
        src/widgets/lv_btnmatrix.c \
        src/widgets/lv_canvas.c \
        src/widgets/lv_checkbox.c \
        src/widgets/lv_dropdown.c \
        src/widgets/lv_img.c \
        src/widgets/lv_label.c \
        src/widgets/lv_line.c \
        src/widgets/lv_objx_templ.c \
        src/widgets/lv_roller.c \
        src/widgets/lv_slider.c \
        src/widgets/lv_switch.c \
        src/widgets/lv_table.c \
        src/widgets/lv_textarea.c

HEADERS += \
    SDL2/SDL.h \
    SDL2/SDL_assert.h \
    SDL2/SDL_atomic.h \
    SDL2/SDL_audio.h \
    SDL2/SDL_bits.h \
    SDL2/SDL_blendmode.h \
    SDL2/SDL_clipboard.h \
    SDL2/SDL_config.h \
    SDL2/SDL_cpuinfo.h \
    SDL2/SDL_egl.h \
    SDL2/SDL_endian.h \
    SDL2/SDL_error.h \
    SDL2/SDL_events.h \
    SDL2/SDL_filesystem.h \
    SDL2/SDL_gamecontroller.h \
    SDL2/SDL_gesture.h \
    SDL2/SDL_haptic.h \
    SDL2/SDL_hidapi.h \
    SDL2/SDL_hints.h \
    SDL2/SDL_joystick.h \
    SDL2/SDL_keyboard.h \
    SDL2/SDL_keycode.h \
    SDL2/SDL_loadso.h \
    SDL2/SDL_locale.h \
    SDL2/SDL_log.h \
    SDL2/SDL_main.h \
    SDL2/SDL_messagebox.h \
    SDL2/SDL_metal.h \
    SDL2/SDL_misc.h \
    SDL2/SDL_mouse.h \
    SDL2/SDL_mutex.h \
    SDL2/SDL_name.h \
    SDL2/SDL_opengl.h \
    SDL2/SDL_opengl_glext.h \
    SDL2/SDL_opengles.h \
    SDL2/SDL_opengles2.h \
    SDL2/SDL_opengles2_gl2.h \
    SDL2/SDL_opengles2_gl2ext.h \
    SDL2/SDL_opengles2_gl2platform.h \
    SDL2/SDL_opengles2_khrplatform.h \
    SDL2/SDL_pixels.h \
    SDL2/SDL_platform.h \
    SDL2/SDL_power.h \
    SDL2/SDL_quit.h \
    SDL2/SDL_rect.h \
    SDL2/SDL_render.h \
    SDL2/SDL_revision.h \
    SDL2/SDL_rwops.h \
    SDL2/SDL_scancode.h \
    SDL2/SDL_sensor.h \
    SDL2/SDL_shape.h \
    SDL2/SDL_stdinc.h \
    SDL2/SDL_surface.h \
    SDL2/SDL_system.h \
    SDL2/SDL_syswm.h \
    SDL2/SDL_test.h \
    SDL2/SDL_test_assert.h \
    SDL2/SDL_test_common.h \
    SDL2/SDL_test_compare.h \
    SDL2/SDL_test_crc32.h \
    SDL2/SDL_test_font.h \
    SDL2/SDL_test_fuzzer.h \
    SDL2/SDL_test_harness.h \
    SDL2/SDL_test_images.h \
    SDL2/SDL_test_log.h \
    SDL2/SDL_test_md5.h \
    SDL2/SDL_test_memory.h \
    SDL2/SDL_test_random.h \
    SDL2/SDL_thread.h \
    SDL2/SDL_timer.h \
    SDL2/SDL_touch.h \
    SDL2/SDL_types.h \
    SDL2/SDL_version.h \
    SDL2/SDL_video.h \
    SDL2/SDL_vulkan.h \
    SDL2/begin_code.h \
    SDL2/close_code.h \
    demos/benchmark/lv_demo_benchmark.h \
    demos/keypad_encoder/lv_demo_keypad_encoder.h \
    demos/lv_demos.h \
    demos/lvgl_app/lvgl_app.h/menu_app.h \
    demos/lvgl_app/lvgl_app.h/oscilloscope_app.h \
    demos/lvgl_app/lvgl_app.h/power_app.h \
    demos/lvgl_app/lvgl_app.h/signal_app.h \
    demos/music/assets/spectrum_1.h \
    demos/music/assets/spectrum_2.h \
    demos/music/assets/spectrum_3.h \
    demos/music/lv_demo_music.h \
    demos/music/lv_demo_music_list.h \
    demos/music/lv_demo_music_main.h \
    demos/stress/lv_demo_stress.h \
    demos/widgets/lv_demo_widgets.h \
    lv_conf.h \
    lv_drivers/display/GC9A01.h \
    lv_drivers/display/ILI9341.h \
    lv_drivers/display/R61581.h \
    lv_drivers/display/SHARP_MIP.h \
    lv_drivers/display/SSD1963.h \
    lv_drivers/display/ST7565.h \
    lv_drivers/display/UC1610.h \
    lv_drivers/display/drm.h \
    lv_drivers/display/fbdev.h \
    lv_drivers/display/monitor.h \
    lv_drivers/gtkdrv/gtkdrv.h \
    lv_drivers/indev/AD_touch.h \
    lv_drivers/indev/FT5406EE8.h \
    lv_drivers/indev/XPT2046.h \
    lv_drivers/indev/evdev.h \
    lv_drivers/indev/keyboard.h \
    lv_drivers/indev/libinput_drv.h \
    lv_drivers/indev/mouse.h \
    lv_drivers/indev/mousewheel.h \
    lv_drivers/indev/xkb.h \
    lv_drivers/lv_drv_conf_template.h \
    lv_drivers/sdl/sdl.h \
    lv_drivers/sdl/sdl_gpu.h \
    lv_drivers/wayland/wayland.h \
    lv_drivers/win32drv/win32drv.h \
    lv_drivers/win_drv.h \
    lv_drv_conf.h \
    lvgl.h \
    src/core/lv_disp.h \
    src/core/lv_event.h \
    src/core/lv_group.h \
    src/core/lv_indev.h \
    src/core/lv_indev_scroll.h \
    src/core/lv_obj.h \
    src/core/lv_obj_class.h \
    src/core/lv_obj_draw.h \
    src/core/lv_obj_pos.h \
    src/core/lv_obj_scroll.h \
    src/core/lv_obj_style.h \
    src/core/lv_obj_style_gen.h \
    src/core/lv_obj_tree.h \
    src/core/lv_refr.h \
    src/core/lv_theme.h \
    src/draw/lv_draw.h \
    src/draw/lv_draw_arc.h \
    src/draw/lv_draw_img.h \
    src/draw/lv_draw_label.h \
    src/draw/lv_draw_line.h \
    src/draw/lv_draw_mask.h \
    src/draw/lv_draw_rect.h \
    src/draw/lv_draw_triangle.h \
    src/draw/lv_img_buf.h \
    src/draw/lv_img_cache.h \
    src/draw/lv_img_decoder.h \
    src/draw/nxp_pxp/lv_gpu_nxp_pxp.h \
    src/draw/nxp_pxp/lv_gpu_nxp_pxp_osa.h \
    src/draw/nxp_vglite/lv_gpu_nxp_vglite.h \
    src/draw/sdl/lv_draw_sdl.h \
    src/draw/sdl/lv_draw_sdl_composite.h \
    src/draw/sdl/lv_draw_sdl_img.h \
    src/draw/sdl/lv_draw_sdl_mask.h \
    src/draw/sdl/lv_draw_sdl_priv.h \
    src/draw/sdl/lv_draw_sdl_rect.h \
    src/draw/sdl/lv_draw_sdl_stack_blur.h \
    src/draw/sdl/lv_draw_sdl_texture_cache.h \
    src/draw/sdl/lv_draw_sdl_utils.h \
    src/draw/stm32_dma2d/lv_gpu_stm32_dma2d.h \
    src/draw/sw/lv_draw_sw.h \
    src/draw/sw/lv_draw_sw_blend.h \
    src/draw/sw/lv_draw_sw_dither.h \
    src/draw/sw/lv_draw_sw_gradient.h \
    src/extra/layouts/flex/lv_flex.h \
    src/extra/layouts/grid/lv_grid.h \
    src/extra/layouts/lv_layouts.h \
    src/extra/libs/bmp/lv_bmp.h \
    src/extra/libs/ffmpeg/lv_ffmpeg.h \
    src/extra/libs/freetype/lv_freetype.h \
    src/extra/libs/fsdrv/lv_fsdrv.h \
    src/extra/libs/gif/gifdec.h \
    src/extra/libs/gif/lv_gif.h \
    src/extra/libs/lv_libs.h \
    src/extra/libs/png/lodepng.h \
    src/extra/libs/png/lv_png.h \
    src/extra/libs/qrcode/lv_qrcode.h \
    src/extra/libs/qrcode/qrcodegen.h \
    src/extra/libs/rlottie/lv_rlottie.h \
    src/extra/libs/sjpg/lv_sjpg.h \
    src/extra/libs/sjpg/tjpgd.h \
    src/extra/libs/sjpg/tjpgdcnf.h \
    src/extra/lv_extra.h \
    src/extra/others/gridnav/lv_gridnav.h \
    src/extra/others/lv_others.h \
    src/extra/others/monkey/lv_monkey.h \
    src/extra/others/snapshot/lv_snapshot.h \
    src/extra/themes/basic/lv_theme_basic.h \
    src/extra/themes/default/lv_theme_default.h \
    src/extra/themes/lv_themes.h \
    src/extra/themes/mono/lv_theme_mono.h \
    src/extra/widgets/animimg/lv_animimg.h \
    src/extra/widgets/calendar/lv_calendar.h \
    src/extra/widgets/calendar/lv_calendar_header_arrow.h \
    src/extra/widgets/calendar/lv_calendar_header_dropdown.h \
    src/extra/widgets/chart/lv_chart.h \
    src/extra/widgets/colorwheel/lv_colorwheel.h \
    src/extra/widgets/imgbtn/lv_imgbtn.h \
    src/extra/widgets/keyboard/lv_keyboard.h \
    src/extra/widgets/led/lv_led.h \
    src/extra/widgets/list/lv_list.h \
    src/extra/widgets/lv_widgets.h \
    src/extra/widgets/menu/lv_menu.h \
    src/extra/widgets/meter/lv_meter.h \
    src/extra/widgets/msgbox/lv_msgbox.h \
    src/extra/widgets/span/lv_span.h \
    src/extra/widgets/spinbox/lv_spinbox.h \
    src/extra/widgets/spinner/lv_spinner.h \
    src/extra/widgets/tabview/lv_tabview.h \
    src/extra/widgets/tileview/lv_tileview.h \
    src/extra/widgets/win/lv_win.h \
    src/font/lv_font.h \
    src/font/lv_font_fmt_txt.h \
    src/font/lv_font_loader.h \
    src/font/lv_symbol_def.h \
    src/hal/lv_hal.h \
    src/hal/lv_hal_disp.h \
    src/hal/lv_hal_indev.h \
    src/hal/lv_hal_tick.h \
    src/lv_api_map.h \
    src/lv_conf_internal.h \
    src/lv_conf_kconfig.h \
    src/lvgl.h \
    src/misc/lv_anim.h \
    src/misc/lv_anim_timeline.h \
    src/misc/lv_area.h \
    src/misc/lv_assert.h \
    src/misc/lv_async.h \
    src/misc/lv_bidi.h \
    src/misc/lv_color.h \
    src/misc/lv_fs.h \
    src/misc/lv_gc.h \
    src/misc/lv_ll.h \
    src/misc/lv_log.h \
    src/misc/lv_lru.h \
    src/misc/lv_math.h \
    src/misc/lv_mem.h \
    src/misc/lv_printf.h \
    src/misc/lv_style.h \
    src/misc/lv_style_gen.h \
    src/misc/lv_templ.h \
    src/misc/lv_timer.h \
    src/misc/lv_tlsf.h \
    src/misc/lv_txt.h \
    src/misc/lv_txt_ap.h \
    src/misc/lv_types.h \
    src/misc/lv_utils.h \
    src/widgets/lv_arc.h \
    src/widgets/lv_bar.h \
    src/widgets/lv_btn.h \
    src/widgets/lv_btnmatrix.h \
    src/widgets/lv_canvas.h \
    src/widgets/lv_checkbox.h \
    src/widgets/lv_dropdown.h \
    src/widgets/lv_img.h \
    src/widgets/lv_label.h \
    src/widgets/lv_line.h \
    src/widgets/lv_objx_templ.h \
    src/widgets/lv_roller.h \
    src/widgets/lv_slider.h \
    src/widgets/lv_switch.h \
    src/widgets/lv_table.h \
    src/widgets/lv_textarea.h
